// Generated by delombok at Thu Mar 14 10:33:26 CST 2013
package org.jrenner.glances;

/**
 * Data structure for getDiskIO() results
 */

public class DiskIO {

    private String disk_name;
    private int read_bytes;
    private int write_bytes;

    @Override
    public String toString() {
        String writeText = Glances.autoUnit(write_bytes) + "B";
        String readText = Glances.autoUnit(read_bytes) + "B";
        return String.format("Disk[%s]: write: %s, read: %s", disk_name, writeText, readText);
    }

    public String getDiskName() {
        return this.disk_name;
    }

    public int getReadBytes() {
        return this.read_bytes;
    }

    public int getWriteBytes() {
        return this.write_bytes;
    }
}