// Generated by delombok at Thu Mar 14 10:33:26 CST 2013
package org.jrenner.glances;

/**
 * Data structure for getLoad()
 */

public class Load {

    private double min1;
    private double min5;
    private double min15;

    @Override
    public String toString() {
        String text = String.format("Load: min1: %.2f, min5: %.2f, min15: %.2f", min1, min5, min15);
        return text;
    }

    /** @return load for last minute */
    public double getMin1() {
        return this.min1;
    }

    /** @return load for last 5 minutes */
    public double getMin5() {
        return this.min5;
    }


    /** @return load for last 15 minutes */
    public double getMin15() {
        return this.min15;
    }
}