// Generated by delombok at Thu Mar 14 10:33:26 CST 2013
package org.jrenner.glances;

/**
 * Data structure for getMem()
 */

public class Memory {

    private long inactive;
    private long cached;
    private long used;
    private long buffers;
    private long active;
    private long total;
    private double percent; // percent in usage
    private long free;

    @Override
    public String toString() {
        String inactiveText = Glances.autoUnit(inactive);
        //String cachedText = Glances.autoUnit(cached);
        String usedText = Glances.autoUnit(used);
        //String buffersText = Glances.autoUnit(buffers);
        String activeText = Glances.autoUnit(active);
        String totalText = Glances.autoUnit(total);
        String percentText = String.format("%.1f", percent);
        String freeText = Glances.autoUnit(free);
        String text = String.format("Memory: inactive: %s, active: %s", inactiveText, activeText);
        text += String.format(" used: %s, total: %s", usedText, totalText);
        text += String.format(" percent: %s, free: %s", percentText, freeText);
        return text;
    }

    public long getInactive() {
        return this.inactive;
    }

    public long getCached() {
        return this.cached;
    }

    public long getUsed() {
        return this.used;
    }

    public long getBuffers() {
        return this.buffers;
    }

    public long getActive() {
        return this.active;
    }

    public long getTotal() {
        return this.total;
    }

    public double getPercent() {
        return this.percent;
    }

    public long getFree() {
        return this.free;
    }
}