// Generated by delombok at Thu Mar 14 10:33:26 CST 2013
package org.jrenner.glances;

/**
 * Data structure for getNetwork() results
 */
// TODO methods for returning one field in a formatted string i.e. "Rx: 1.76MB"

public class NetworkInterface {

    private String interface_name;
    private float time_since_update;
    private long rx;
    private long tx;
    private long cumulative_rx;
    private long cumulative_tx;

    @Override
    public String toString() {
        char suffix = 'B';
        String rxText = Glances.autoUnit(getRxPerSecond()) + suffix;
        String txText = Glances.autoUnit(getTxPerSecond()) + suffix;
        String cumulative_rxText = Glances.autoUnit(getCumulativeRx()) + suffix;
        String cumulative_txText = Glances.autoUnit(getCumulativeTx()) + suffix;
        String text = String.format("Net[%s]: Rx/s: %s Tx/s: %s TOTAL: Rx/Tx %s / %s",
                interface_name, rxText, txText, cumulative_rxText, cumulative_txText);
        return text;
    }

    public String getInterfaceName() {
        return this.interface_name;
    }

    /** @return time in seconds since last update */
    public float getTimeSinceUpdate() {
        return this.time_since_update;
    }

    /** @return bytes received per second since last update*/
    public long getRxPerSecond() {
        return (long) (getRx() / getTimeSinceUpdate());
    }

    /** @return bytes sent per second since last update*/
    public long getTxPerSecond() {
        return (long) (getTx() / getTimeSinceUpdate());
    }

    /** @return bytes received since last update*/
    public long getRx() {
        return this.rx;
    }

    /** @return bytes sent since last update */
    public long getTx() {
        return this.tx;
    }

    /** @return cumulative amount of bytes received */
    public long getCumulativeRx() {
        return this.cumulative_rx;
    }


    /** @return cumulative amount of bytes sent */
    public long getCumulativeTx() {
        return this.cumulative_tx;
    }
}