// Generated by delombok at Thu Mar 14 10:33:26 CST 2013
package org.jrenner.glances;

/**
 * Data structure for getSensors()
 */

public class Sensor {

    private String label;
    private int value;

    @Override
    public String toString() {
        return String.format("Sensor: %s value: %d", label, value);
    }

    public String getLabel() {
        return this.label;
    }

    public int getValue() {
        return this.value;
    }
}