// Generated by delombok at Thu Mar 14 10:33:26 CST 2013
package org.jrenner.glances;

/**
 * Data structure for getSystem()
 */

public class SystemInfo {

    private String platform;
    private String host_name;
    private String os_name;
    private String os_version;
    private String linux_distro;

    @Override
    public String toString() {
        String text = String.format("%s %s %s", os_name, platform, os_version);
        // these conditionals could use some testing
        if (linux_distro != null) {
            text += " " + linux_distro;
        }
        if (host_name != null) {
            text += " " + host_name;
        }
        return text;
    }

    public String getPlatform() {
        return this.platform;
    }

    public String getHostName() {
        return this.host_name;
    }
    
    public String getOsName() {
        return this.os_name;
    }

    public String getOsVersion() {
        return this.os_version;
    }
    
    public String getLinuxDistro() {
        return this.linux_distro;
    }
}