// Generated by delombok at Thu Mar 14 10:33:26 CST 2013
package org.jrenner.glances;

/**
 * Data structure for getFs()
 * The numbers stored are in bytes
 */

public class FileSystem {

    private String mnt_point;
    private String device_name;
    private String fs_type;
    private long used;
    private long avail;
    private long size;

    @Override
    public String toString() {
        String usedText = Glances.autoUnit(used) + "B"; // always Bytes
        String availText = Glances.autoUnit(avail) + "B";
        String sizeText = Glances.autoUnit(size) + "B";
        String text = String.format("[%s]: %s (%s) used: %s, avail: %s, size: %s", device_name, mnt_point, fs_type, usedText, availText, sizeText);
        return text;
    }

    public String getMountPoint() {
        return this.mnt_point;
    }

    public String getDeviceName() {
        return this.device_name;
    }

    public String getFileSystemType() {
        return this.fs_type;
    }

    public long getUsed() {
        return this.used;
    }

    public long getAvailable() {
        return this.avail;
    }

    public long getSize() {
        return this.size;
    }
}