// Generated by delombok at Thu Mar 14 10:33:26 CST 2013
package org.jrenner.glances;

/**
 * Data structure for getMemSwap()
 */

public class MemorySwap {

    private long total;
    private float percent;
    private long free;
    private long used;

    @Override
    public String toString() {
        String totalText = Glances.autoUnit(total);
        String percentText = String.format("%.1f", percent);
        String freeText = Glances.autoUnit(free);
        String usedText = Glances.autoUnit(used);
        String text = String.format("Swap: free: %s, used: %s total: %s, percent: %s", freeText, usedText, totalText, percentText);
        return text;
    }

    public long getTotal() {
        return this.total;
    }

    public float getPercent() {
        return this.percent;
    }

    public long getFree() {
        return this.free;
    }

    public long getUsed() {
        return this.used;
    }
}